use std::{
    fs,
    path::{Path, PathBuf},
};

use hdf5::{
    types::{VarLenAscii, VarLenUnicode},
    Dataset, File, Group, Location,
};
use tempfile::TempPath;

use crate::{
    error::{Error, Result},
    normalization::{
        compute_cis_coverage_pair_for_storage, compute_global_coverage_with_pool,
        compute_ice_from_shared_coverage, compute_kr_from_shared_coverage_owned,
        compute_stored_normalizations_with_pool, Normalization, SparseContactMatrix,
        SymmetricCsrCounter,
    },
    zoomify::{
        build_worker_pool, rust_zoomify_with_pool, validate_compression_level, AggregationMode,
        ZoomifyExecution, DEFAULT_COMPRESSION_LEVEL,
    },
};

/// Required base resolution for input COOL files and generated MCOOL ladders.
pub const BASE_RESOLUTION: u64 = 1_000;

const NORMALIZATION_VERSION: u32 = 4;
const KR_ALGORITHM: &str = "whole-assembly-compact-csr-continuation-warm-start-v4";
const RUNTIME_NORMALIZATION_MEMORY_NUMERATOR: usize = 4;
const RUNTIME_NORMALIZATION_MEMORY_DENOMINATOR: usize = 5;
const FALLBACK_RUNTIME_NORMALIZATION_MEMORY_BYTES: usize = 512 * 1024 * 1024;
const NORMALIZATION_IO_CHUNK_PIXELS: usize = 1_000_000;
const MAX_FUSED_NORMALIZATION_VECTOR_BYTES: usize = 128 * 1024 * 1024;

/// Default 10-level resolution ladder generated by [`generate`].
pub const DEFAULT_RESOLUTIONS: &[u64] = &[
    1_000, 5_000, 10_000, 25_000, 50_000, 100_000, 250_000, 500_000, 1_000_000, 2_500_000,
];

const STORED_NORMALIZATIONS_WITH_KR: [Normalization; 4] = [
    Normalization::Ice,
    Normalization::Kr,
    Normalization::Vc,
    Normalization::VcSqrt,
];
const STORED_NORMALIZATIONS_WITHOUT_KR: [Normalization; 3] =
    [Normalization::Ice, Normalization::Vc, Normalization::VcSqrt];

/// Options controlling MCOOL generation and final output installation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerationOptions {
    pub resolutions: Vec<u64>,
    pub threads: usize,
    pub level_parallelism: usize,
    pub aggregation_mode: AggregationMode,
    /// Gzip/deflate level for datasets created by the generator.
    pub compression_level: u8,
    /// Smallest output resolution that receives a true KR vector.
    pub kr_min_resolution: u64,
    pub force: bool,
}

impl Default for GenerationOptions {
    fn default() -> Self {
        Self {
            resolutions: DEFAULT_RESOLUTIONS.to_vec(),
            threads: std::thread::available_parallelism()
                .map_or(1, usize::from)
                .clamp(1, 8),
            level_parallelism: 2,
            aggregation_mode: AggregationMode::Pyramid,
            compression_level: DEFAULT_COMPRESSION_LEVEL,
            kr_min_resolution: BASE_RESOLUTION,
            force: false,
        }
    }
}

/// Progress events emitted synchronously while an output is generated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Progress {
    ValidatingInput,
    Zoomifying {
        resolutions: Vec<u64>,
        aggregation_mode: AggregationMode,
    },
    Normalizing {
        resolution: u64,
        normalization: Normalization,
    },
    NormalizationFallback {
        resolution: u64,
        normalization: Normalization,
        reason: String,
    },
    Finalizing,
    Complete,
}

/// Summary of a successfully generated and installed MCOOL file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerationReport {
    pub output: PathBuf,
    pub resolutions: Vec<u64>,
    pub kr_resolutions: Vec<u64>,
    pub kr_min_resolution: u64,
    pub normalization_columns: Vec<&'static str>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct CoolInputSummary {
    bins: usize,
    pixels: usize,
}

struct LevelNormalizationInput {
    matrix: SparseContactMatrix,
    bin_chrom_ids: Vec<u32>,
    chromosome_count: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct NormalizationColumnSpec {
    name: &'static str,
    divisive: bool,
}

fn runtime_normalization_memory_budget_bytes(available_bytes: usize) -> usize {
    ((available_bytes as u128) * (RUNTIME_NORMALIZATION_MEMORY_NUMERATOR as u128)
        / (RUNTIME_NORMALIZATION_MEMORY_DENOMINATOR as u128))
        .min(usize::MAX as u128) as usize
}

#[cfg(target_os = "macos")]
#[allow(deprecated)]
fn available_system_memory_bytes() -> Option<usize> {
    static HOST_PORT: std::sync::OnceLock<libc::mach_port_t> = std::sync::OnceLock::new();
    let page_size = unsafe { libc::sysconf(libc::_SC_PAGESIZE) };
    if page_size <= 0 {
        return None;
    }

    let host = *HOST_PORT.get_or_init(|| unsafe { libc::mach_host_self() });
    let mut statistics = std::mem::MaybeUninit::<libc::vm_statistics64_data_t>::zeroed();
    let mut count = libc::HOST_VM_INFO64_COUNT;
    let status = unsafe {
        libc::host_statistics64(
            host,
            libc::HOST_VM_INFO64,
            statistics.as_mut_ptr().cast::<libc::integer_t>(),
            &mut count,
        )
    };
    if status != libc::KERN_SUCCESS {
        return None;
    }
    let statistics = unsafe { statistics.assume_init() };
    let available_pages = u64::from(statistics.free_count)
        .saturating_add(u64::from(statistics.inactive_count))
        .saturating_add(u64::from(statistics.speculative_count));
    usize::try_from(available_pages.saturating_mul(page_size as u64)).ok()
}

#[cfg(target_os = "linux")]
fn available_system_memory_bytes() -> Option<usize> {
    let meminfo = fs::read_to_string("/proc/meminfo").ok()?;
    let kibibytes = meminfo.lines().find_map(|line| {
        let value = line.strip_prefix("MemAvailable:")?.trim();
        value.split_whitespace().next()?.parse::<usize>().ok()
    })?;
    kibibytes.checked_mul(1024)
}

#[cfg(not(any(target_os = "macos", target_os = "linux")))]
fn available_system_memory_bytes() -> Option<usize> {
    None
}

fn estimated_normalization_peak_bytes(pixel_count: usize, bin_count: usize) -> usize {
    // A symmetric CSR needs at most two (u32, f64) entries per source pixel.
    // Pixel columns are read twice in bounded chunks, so no full COO coexists
    // with the CSR. The bin allowance covers row offsets and ICE/KR work vectors.
    pixel_count
        .saturating_mul(24)
        .saturating_add(bin_count.saturating_mul(160))
}

fn ensure_normalization_memory_budget(
    resolution: u64,
    pixel_count: usize,
    bin_count: usize,
) -> Result<()> {
    let estimated_bytes = estimated_normalization_peak_bytes(pixel_count, bin_count);
    let (budget_bytes, availability) = match available_system_memory_bytes() {
        Some(available_bytes) => (
            runtime_normalization_memory_budget_bytes(available_bytes),
            format!(
                "{} MiB currently available; the 80% budget is {} MiB",
                available_bytes / (1024 * 1024),
                runtime_normalization_memory_budget_bytes(available_bytes) / (1024 * 1024),
            ),
        ),
        None => (
            FALLBACK_RUNTIME_NORMALIZATION_MEMORY_BYTES,
            format!(
                "available memory could not be determined; the fallback budget is {} MiB",
                FALLBACK_RUNTIME_NORMALIZATION_MEMORY_BYTES / (1024 * 1024),
            ),
        ),
    };
    if estimated_bytes > budget_bytes {
        return Err(generation_error(format!(
            "resolution {resolution} normalization estimates about {} MiB for {bin_count} bins and {pixel_count} pixels, but {availability}",
            estimated_bytes / (1024 * 1024),
        )));
    }
    Ok(())
}

/// Generate a normalized multi-resolution Cooler from a fixed 1 kb COOL file.
///
/// The output is built in an exclusively created temporary path beside the
/// destination, synchronized, and installed only after every level succeeds.
/// Without `force`, a destination created concurrently is never overwritten.
pub fn generate<F>(
    input: &Path,
    output: &Path,
    options: &GenerationOptions,
    mut progress: F,
) -> Result<GenerationReport>
where
    F: FnMut(Progress),
{
    progress(Progress::ValidatingInput);
    validate_generation_paths(input, output, options.force)?;
    validate_resolution_ladder(&options.resolutions)?;
    validate_kr_min_resolution(options.kr_min_resolution)?;
    validate_compression_level(options.compression_level)?;
    validate_fixed_1k_input(input)?;

    let partial = partial_output_path(output)?;
    let partial_path: &Path = partial.as_ref();
    progress(Progress::Zoomifying {
        resolutions: options.resolutions.clone(),
        aggregation_mode: options.aggregation_mode,
    });
    let zoomify_pool = build_worker_pool(options.threads)?;
    rust_zoomify_with_pool(
        input,
        partial_path,
        &options.resolutions,
        &zoomify_pool,
        ZoomifyExecution::new(
            options.threads,
            options.level_parallelism,
            options.aggregation_mode,
            options.compression_level,
        ),
    )?;
    drop(zoomify_pool);
    if !partial_path.is_file() {
        return Err(generation_error(format!(
            "native Rust zoomify reported success but did not create {}",
            partial_path.display()
        )));
    }
    release_allocator_spare_pages();
    // Keep exactly one bounded Rayon pool alive at a time. Recreating it at
    // the phase boundary preserves one `--threads` budget without retaining
    // zoomify worker-local allocation caches throughout large KR runs.
    let worker_pool = build_worker_pool(options.threads)?;

    for &resolution in &options.resolutions {
        let stored_normalizations =
            stored_normalizations_for_resolution(resolution, options.kr_min_resolution);
        let include_kr = stored_normalizations.contains(&Normalization::Kr);
        let file = open_generated_mcool(partial_path)?;
        let level = generated_resolution_group(&file, resolution)?;
        validate_generated_level(&level, resolution)?;
        let level_input = read_normalization_input(&level, resolution)?;
        let fused_vector_bytes = level_input
            .matrix
            .bin_count()
            .saturating_mul(std::mem::size_of::<f64>())
            .saturating_mul(6);
        if include_kr && fused_vector_bytes <= MAX_FUSED_NORMALIZATION_VECTOR_BYTES {
            let results = compute_stored_normalizations_with_pool(
                &level_input.matrix,
                &level_input.bin_chrom_ids,
                level_input.chromosome_count,
                &worker_pool,
                &|| false,
                |normalization| {
                    progress(Progress::Normalizing {
                        resolution,
                        normalization,
                    });
                },
            )?;

            write_normalization_column(
                &level,
                Normalization::Ice,
                &results.ice.weights,
                options.compression_level,
            )?;
            if !results.ice.converged {
                record_ice_fallback(
                    &level,
                    resolution,
                    results.ice.relative_variance,
                    &mut progress,
                )?;
            }
            write_normalization_column(
                &level,
                Normalization::Kr,
                &results.kr.weights,
                options.compression_level,
            )?;
            annotate_normalization_metric(
                &level,
                Normalization::Kr,
                "cool2mcool_coverage_percentile",
                results.kr.coverage_percentile,
            )?;
            write_normalization_column(
                &level,
                Normalization::Vc,
                &results.vc,
                options.compression_level,
            )?;
            write_normalization_column(
                &level,
                Normalization::VcSqrt,
                &results.vc_sqrt,
                options.compression_level,
            )?;
        } else {
            let LevelNormalizationInput {
                matrix,
                bin_chrom_ids,
                chromosome_count,
            } = level_input;
            let bin_count = matrix.bin_count();
            let perf_enabled = std::env::var("COOL2MCOOL_PERF_LOG").as_deref() == Ok("1");
            let phase_started = std::time::Instant::now();
            let coverage = compute_global_coverage_with_pool(&matrix, &worker_pool, &|| false)?;
            if perf_enabled {
                eprintln!(
                    "COOL2MCOOL_PERF event=normalization_coverage status=complete bins={} source_pixels=shared elapsed_ms={}",
                    bin_count,
                    phase_started.elapsed().as_millis(),
                );
            }

            progress(Progress::Normalizing {
                resolution,
                normalization: Normalization::Ice,
            });
            let phase_started = std::time::Instant::now();
            {
                let ice =
                    compute_ice_from_shared_coverage(&matrix, &coverage, &worker_pool, &|| false)?;
                if perf_enabled {
                    eprintln!(
                        "COOL2MCOOL_PERF event=normalization_ice status=complete bins={} elapsed_ms={}",
                        bin_count,
                        phase_started.elapsed().as_millis(),
                    );
                }
                write_normalization_column(
                    &level,
                    Normalization::Ice,
                    &ice.weights,
                    options.compression_level,
                )?;
                if !ice.converged {
                    record_ice_fallback(&level, resolution, ice.relative_variance, &mut progress)?;
                }
            }

            progress(Progress::Normalizing {
                resolution,
                normalization: Normalization::Vc,
            });
            progress(Progress::Normalizing {
                resolution,
                normalization: Normalization::VcSqrt,
            });
            let phase_started = std::time::Instant::now();
            let (vc, vc_sqrt) = compute_cis_coverage_pair_for_storage(
                &matrix,
                &bin_chrom_ids,
                chromosome_count,
                &|| false,
            )?;
            if perf_enabled {
                eprintln!(
                    "COOL2MCOOL_PERF event=normalization_vc_pair status=complete bins={} elapsed_ms={}",
                    bin_count,
                    phase_started.elapsed().as_millis(),
                );
            }
            write_normalization_column(&level, Normalization::Vc, &vc, options.compression_level)?;
            write_normalization_column(
                &level,
                Normalization::VcSqrt,
                &vc_sqrt,
                options.compression_level,
            )?;
            drop(vc);
            drop(vc_sqrt);
            drop(bin_chrom_ids);

            if include_kr {
                progress(Progress::Normalizing {
                    resolution,
                    normalization: Normalization::Kr,
                });
                let phase_started = std::time::Instant::now();
                let kr = compute_kr_from_shared_coverage_owned(
                    matrix,
                    &coverage,
                    &worker_pool,
                    &|| false,
                )?;
                if perf_enabled {
                    eprintln!(
                        "COOL2MCOOL_PERF event=normalization_kr status=complete bins={} elapsed_ms={}",
                        bin_count,
                        phase_started.elapsed().as_millis(),
                    );
                }
                write_normalization_column(
                    &level,
                    Normalization::Kr,
                    &kr.weights,
                    options.compression_level,
                )?;
                annotate_normalization_metric(
                    &level,
                    Normalization::Kr,
                    "cool2mcool_coverage_percentile",
                    kr.coverage_percentile,
                )?;
            } else {
                remove_normalization_column(&level, Normalization::Kr)?;
            }
        }
        write_level_normalization_manifest(&level, stored_normalizations)?;
        validate_stored_normalizations(&level, resolution, stored_normalizations)?;
        file.flush().map_err(|error| {
            generation_error(format!(
                "failed to flush resolution {resolution} normalizations: {error}"
            ))
        })?;
    }
    let file = open_generated_mcool(partial_path)?;
    write_generation_manifest(&file, &options.resolutions, options.kr_min_resolution)?;
    file.flush()
        .map_err(|error| generation_error(format!("failed to flush generated mcool: {error}")))?;
    drop(file);
    apply_input_file_permissions(input, partial_path)?;
    sync_completed_partial(partial_path)?;

    progress(Progress::Finalizing);
    install_partial_output(partial, output, options.force)?;
    progress(Progress::Complete);

    let kr_resolutions = options
        .resolutions
        .iter()
        .copied()
        .filter(|resolution| *resolution >= options.kr_min_resolution)
        .collect::<Vec<_>>();
    let file_normalizations = stored_normalizations_for_kr(!kr_resolutions.is_empty());
    Ok(GenerationReport {
        output: output.to_path_buf(),
        resolutions: options.resolutions.clone(),
        kr_resolutions,
        kr_min_resolution: options.kr_min_resolution,
        normalization_columns: file_normalizations
            .iter()
            .copied()
            .map(|normalization| normalization_column_spec(normalization).name)
            .collect(),
    })
}

#[cfg(target_os = "macos")]
fn release_allocator_spare_pages() {
    extern "C" {
        fn malloc_zone_pressure_relief(
            zone: *mut libc::malloc_zone_t,
            goal: libc::size_t,
        ) -> libc::size_t;
    }
    // SAFETY: the default malloc zone is process-owned and pressure relief only
    // asks it to return currently unused pages; it cannot invalidate live
    // allocations. Run only at phase boundaries while the shared pool is idle.
    unsafe {
        malloc_zone_pressure_relief(libc::malloc_default_zone(), 0);
    }
}

#[cfg(all(target_os = "linux", target_env = "gnu"))]
fn release_allocator_spare_pages() {
    // SAFETY: malloc_trim releases only free arena pages and does not move live
    // allocations.
    unsafe {
        libc::malloc_trim(0);
    }
}

#[cfg(not(any(target_os = "macos", all(target_os = "linux", target_env = "gnu"))))]
fn release_allocator_spare_pages() {}

fn record_ice_fallback(
    level: &Group,
    resolution: u64,
    relative_variance: f64,
    progress: &mut impl FnMut(Progress),
) -> Result<()> {
    let reason = format!(
        "ICE did not converge within 200 iterations (relative marginal variance {relative_variance:.6e})",
    );
    progress(Progress::NormalizationFallback {
        resolution,
        normalization: Normalization::Ice,
        reason,
    });
    annotate_normalization_fallback(level, Normalization::Ice, "final-iterate-not-converged")?;
    annotate_normalization_metric(
        level,
        Normalization::Ice,
        "cool2mcool_relative_marginal_variance",
        relative_variance,
    )
}

fn validate_generation_paths(input: &Path, output: &Path, force: bool) -> Result<()> {
    if input.extension().and_then(|value| value.to_str()) != Some("cool") {
        return Err(generation_error(format!(
            "input must end with .cool: {}",
            input.display()
        )));
    }
    if output.extension().and_then(|value| value.to_str()) != Some("mcool") {
        return Err(generation_error(format!(
            "output must end with .mcool: {}",
            output.display()
        )));
    }
    if !input.is_file() {
        return Err(generation_error(format!(
            "input cool file does not exist: {}",
            input.display()
        )));
    }
    let output_parent = parent_directory(output);
    if !output_parent.is_dir() {
        return Err(generation_error(format!(
            "output directory does not exist: {}",
            output_parent.display()
        )));
    }
    if output.exists() && !force {
        return Err(generation_error(format!(
            "output already exists (pass --force to replace it): {}",
            output.display()
        )));
    }

    let canonical_input = fs::canonicalize(input).map_err(|error| {
        generation_error(format!(
            "failed to resolve input path {}: {error}",
            input.display()
        ))
    })?;
    let canonical_output = if output.exists() {
        fs::canonicalize(output).map_err(|error| {
            generation_error(format!(
                "failed to resolve output path {}: {error}",
                output.display()
            ))
        })?
    } else {
        let parent = fs::canonicalize(output_parent).map_err(|error| {
            generation_error(format!(
                "failed to resolve output directory {}: {error}",
                output_parent.display()
            ))
        })?;
        parent.join(
            output
                .file_name()
                .ok_or_else(|| generation_error("output path has no filename"))?,
        )
    };
    if canonical_input == canonical_output {
        return Err(generation_error("input and output paths must be different"));
    }
    Ok(())
}

fn parent_directory(path: &Path) -> &Path {
    path.parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."))
}

fn validate_resolution_ladder(resolutions: &[u64]) -> Result<()> {
    if resolutions.is_empty() {
        return Err(generation_error("resolution ladder cannot be empty"));
    }
    for (index, &resolution) in resolutions.iter().enumerate() {
        if resolution == 0 || resolution % BASE_RESOLUTION != 0 {
            return Err(generation_error(format!(
                "resolution {resolution} must be a positive multiple of {BASE_RESOLUTION}"
            )));
        }
        if index > 0 && resolution <= resolutions[index - 1] {
            return Err(generation_error(
                "resolution ladder must be strictly increasing with no duplicates",
            ));
        }
    }
    Ok(())
}

fn validate_kr_min_resolution(kr_min_resolution: u64) -> Result<()> {
    if kr_min_resolution == 0 || kr_min_resolution % BASE_RESOLUTION != 0 {
        return Err(generation_error(format!(
            "KR minimum resolution must be a positive multiple of {BASE_RESOLUTION}, found {kr_min_resolution}"
        )));
    }
    Ok(())
}

fn stored_normalizations_for_kr(include_kr: bool) -> &'static [Normalization] {
    if include_kr {
        &STORED_NORMALIZATIONS_WITH_KR
    } else {
        &STORED_NORMALIZATIONS_WITHOUT_KR
    }
}

fn stored_normalizations_for_resolution(
    resolution: u64,
    kr_min_resolution: u64,
) -> &'static [Normalization] {
    stored_normalizations_for_kr(resolution >= kr_min_resolution)
}

fn validate_fixed_1k_input(path: &Path) -> Result<CoolInputSummary> {
    let file = File::open(path).map_err(|error| {
        generation_error(format!(
            "failed to open input cool file {}: {error}",
            path.display()
        ))
    })?;
    let format = required_string_attr(&file, "format")?;
    if format != "HDF5::Cooler" {
        return Err(generation_error(format!(
            "input format must be HDF5::Cooler, found {format:?}"
        )));
    }
    let bin_type = required_string_attr(&file, "bin-type")?;
    if bin_type != "fixed" {
        return Err(generation_error(format!(
            "input bin-type must be fixed, found {bin_type:?}"
        )));
    }
    let bin_size = required_u64_attr(&file, "bin-size")?;
    if bin_size != BASE_RESOLUTION {
        return Err(generation_error(format!(
            "input bin-size must be {BASE_RESOLUTION}, found {bin_size}"
        )));
    }
    let storage_mode = optional_string_attr(&file, "storage-mode")?
        .unwrap_or_else(|| "symmetric-upper".to_string());
    if storage_mode != "symmetric-upper" {
        return Err(generation_error(format!(
            "input storage-mode must be symmetric-upper, found {storage_mode:?}"
        )));
    }

    let chromosome_count =
        matching_table_lengths(&file, "chroms", &["chroms/name", "chroms/length"])?;
    if chromosome_count == 0 {
        return Err(generation_error("input chroms table is empty"));
    }
    let bin_count =
        matching_table_lengths(&file, "bins", &["bins/chrom", "bins/start", "bins/end"])?;
    if bin_count == 0 {
        return Err(generation_error("input bins table is empty"));
    }
    let pixel_count = matching_table_lengths(
        &file,
        "pixels",
        &["pixels/bin1_id", "pixels/bin2_id", "pixels/count"],
    )?;

    let bin1_offsets =
        read_u64_dataset(&file.dataset("indexes/bin1_offset").map_err(|error| {
            generation_error(format!("input is missing indexes/bin1_offset: {error}"))
        })?)?;
    if bin1_offsets.len() != bin_count + 1
        || bin1_offsets.first().copied() != Some(0)
        || bin1_offsets.last().copied() != Some(pixel_count as u64)
    {
        return Err(generation_error(format!(
            "indexes/bin1_offset must contain {} entries from 0 through {pixel_count}",
            bin_count + 1
        )));
    }
    if bin1_offsets.windows(2).any(|window| window[0] > window[1]) {
        return Err(generation_error(
            "indexes/bin1_offset must be monotonically nondecreasing",
        ));
    }

    let chromosome_offsets =
        read_u64_dataset(&file.dataset("indexes/chrom_offset").map_err(|error| {
            generation_error(format!("input is missing indexes/chrom_offset: {error}"))
        })?)?;
    if chromosome_offsets.len() != chromosome_count + 1
        || chromosome_offsets.first().copied() != Some(0)
        || chromosome_offsets.last().copied() != Some(bin_count as u64)
    {
        return Err(generation_error(format!(
            "indexes/chrom_offset must contain {} entries from 0 through {bin_count}",
            chromosome_count + 1
        )));
    }
    if chromosome_offsets
        .windows(2)
        .any(|window| window[0] > window[1])
    {
        return Err(generation_error(
            "indexes/chrom_offset must be monotonically nondecreasing",
        ));
    }

    Ok(CoolInputSummary {
        bins: bin_count,
        pixels: pixel_count,
    })
}

fn open_generated_mcool(path: &Path) -> Result<File> {
    File::open_rw(path).map_err(|error| {
        generation_error(format!(
            "failed to open generated mcool {} for normalization: {error}",
            path.display()
        ))
    })
}

fn generated_resolution_group(file: &File, resolution: u64) -> Result<Group> {
    let level_path = format!("resolutions/{resolution}");
    file.group(&level_path).map_err(|error| {
        generation_error(format!("generated mcool is missing /{level_path}: {error}"))
    })
}

fn validate_generated_level(level: &Group, resolution: u64) -> Result<()> {
    let format = required_string_attr(level, "format")?;
    if format != "HDF5::Cooler" {
        return Err(generation_error(format!(
            "resolution {resolution} has invalid format {format:?}"
        )));
    }
    let bin_size = required_u64_attr(level, "bin-size")?;
    if bin_size != resolution {
        return Err(generation_error(format!(
            "resolution group {resolution} declares bin-size {bin_size}"
        )));
    }
    let storage_mode = optional_string_attr(level, "storage-mode")?
        .unwrap_or_else(|| "symmetric-upper".to_string());
    if storage_mode != "symmetric-upper" {
        return Err(generation_error(format!(
            "resolution {resolution} must be symmetric-upper, found {storage_mode:?}"
        )));
    }
    Ok(())
}

fn read_normalization_input(level: &Group, resolution: u64) -> Result<LevelNormalizationInput> {
    let chromosome_count = matching_table_lengths(
        level,
        &format!("resolution {resolution} chromosomes"),
        &["chroms/name", "chroms/length"],
    )?;
    let bin_count = matching_table_lengths(
        level,
        &format!("resolution {resolution} bins"),
        &["bins/chrom", "bins/start", "bins/end"],
    )?;
    let pixel_count = matching_table_lengths(
        level,
        &format!("resolution {resolution} pixels"),
        &["pixels/bin1_id", "pixels/bin2_id", "pixels/count"],
    )?;
    ensure_normalization_memory_budget(resolution, pixel_count, bin_count)?;

    let bin_chrom_dataset = level.dataset("bins/chrom").map_err(|error| {
        generation_error(format!(
            "resolution {resolution} is missing bins/chrom: {error}"
        ))
    })?;
    let mut bin_chrom_ids = Vec::with_capacity(bin_count);
    for start in (0..bin_count).step_by(NORMALIZATION_IO_CHUNK_PIXELS) {
        let end = start
            .saturating_add(NORMALIZATION_IO_CHUNK_PIXELS)
            .min(bin_count);
        let raw = read_u64_dataset_slice(&bin_chrom_dataset, start..end)?;
        if raw.len() != end - start {
            return Err(generation_error(format!(
                "resolution {resolution} bins/chrom changed length while being read"
            )));
        }
        for (offset, chrom) in raw.into_iter().enumerate() {
            let bin = start + offset;
            if chrom >= chromosome_count as u64 {
                return Err(generation_error(format!(
                    "resolution {resolution} bin {bin} references chromosome {chrom} outside {chromosome_count} chromosomes"
                )));
            }
            bin_chrom_ids.push(u32::try_from(chrom).map_err(|_| {
                generation_error(format!(
                    "resolution {resolution} chromosome index {chrom} exceeds u32"
                ))
            })?);
        }
    }

    let bin1_dataset = level.dataset("pixels/bin1_id").map_err(|error| {
        generation_error(format!(
            "resolution {resolution} is missing pixels/bin1_id: {error}"
        ))
    })?;
    let bin2_dataset = level.dataset("pixels/bin2_id").map_err(|error| {
        generation_error(format!(
            "resolution {resolution} is missing pixels/bin2_id: {error}"
        ))
    })?;
    let count_dataset = level.dataset("pixels/count").map_err(|error| {
        generation_error(format!(
            "resolution {resolution} is missing pixels/count: {error}"
        ))
    })?;

    let mut counter = SymmetricCsrCounter::new(bin_count, pixel_count)?;
    let mut previous_pixel = None;
    for start in (0..pixel_count).step_by(NORMALIZATION_IO_CHUNK_PIXELS) {
        let end = start
            .saturating_add(NORMALIZATION_IO_CHUNK_PIXELS)
            .min(pixel_count);
        let (bin1, bin2, counts) =
            read_pixel_chunk(&bin1_dataset, &bin2_dataset, &count_dataset, start..end)?;
        for offset in 0..bin1.len() {
            let pixel_index = start + offset;
            let pixel = (bin1[offset], bin2[offset]);
            if previous_pixel.is_some_and(|previous| previous > pixel) {
                return Err(generation_error(format!(
                    "resolution {resolution} pixels are not sorted at index {pixel_index}"
                )));
            }
            previous_pixel = Some(pixel);
            counter.count_pixel(pixel_index, pixel.0, pixel.1, counts[offset])?;
        }
    }
    let mut builder = counter.into_builder()?;
    for start in (0..pixel_count).step_by(NORMALIZATION_IO_CHUNK_PIXELS) {
        let end = start
            .saturating_add(NORMALIZATION_IO_CHUNK_PIXELS)
            .min(pixel_count);
        let (bin1, bin2, counts) =
            read_pixel_chunk(&bin1_dataset, &bin2_dataset, &count_dataset, start..end)?;
        for offset in 0..bin1.len() {
            builder.push_pixel(start + offset, bin1[offset], bin2[offset], counts[offset])?;
        }
    }
    let matrix = builder.finish()?;
    Ok(LevelNormalizationInput {
        matrix,
        bin_chrom_ids,
        chromosome_count,
    })
}

fn read_pixel_chunk(
    bin1_dataset: &Dataset,
    bin2_dataset: &Dataset,
    count_dataset: &Dataset,
    range: std::ops::Range<usize>,
) -> Result<(Vec<u64>, Vec<u64>, Vec<f64>)> {
    let expected = range.end - range.start;
    let bin1 = read_u64_dataset_slice(bin1_dataset, range.clone())?;
    let bin2 = read_u64_dataset_slice(bin2_dataset, range.clone())?;
    let counts = read_f64_dataset_slice(count_dataset, range)?;
    if bin1.len() != expected || bin2.len() != expected || counts.len() != expected {
        return Err(generation_error(
            "pixel columns changed length while being streamed",
        ));
    }
    Ok((bin1, bin2, counts))
}

fn annotate_normalization_fallback(
    level: &Group,
    normalization: Normalization,
    fallback: &str,
) -> Result<()> {
    let spec = normalization_column_spec(normalization);
    let dataset = level
        .dataset(&format!("bins/{}", spec.name))
        .map_err(|error| {
            generation_error(format!(
                "cannot annotate missing bins/{} fallback: {error}",
                spec.name
            ))
        })?;
    let fallback = fallback
        .parse::<VarLenUnicode>()
        .map_err(|error| generation_error(format!("invalid fallback label: {error}")))?;
    dataset
        .new_attr::<VarLenUnicode>()
        .shape(())
        .create("cool2mcool_fallback")
        .and_then(|attribute| attribute.write_scalar(&fallback))
        .map_err(|error| {
            generation_error(format!(
                "failed to annotate bins/{} fallback: {error}",
                spec.name
            ))
        })
}

fn annotate_normalization_metric(
    level: &Group,
    normalization: Normalization,
    name: &str,
    value: f64,
) -> Result<()> {
    let spec = normalization_column_spec(normalization);
    let dataset = level
        .dataset(&format!("bins/{}", spec.name))
        .map_err(|error| {
            generation_error(format!(
                "cannot annotate missing bins/{} metric: {error}",
                spec.name
            ))
        })?;
    dataset
        .new_attr::<f64>()
        .shape(())
        .create(name)
        .and_then(|attribute| attribute.write_scalar(&value))
        .map_err(|error| {
            generation_error(format!(
                "failed to annotate bins/{} metric {name}: {error}",
                spec.name
            ))
        })
}

fn write_normalization_column(
    level: &Group,
    normalization: Normalization,
    multiplicative_weights: &[f64],
    compression_level: u8,
) -> Result<()> {
    validate_compression_level(compression_level)?;
    let spec = normalization_column_spec(normalization);
    let bins = level.group("bins").map_err(|error| {
        generation_error(format!("generated level is missing bins group: {error}"))
    })?;
    let bin_count = dataset_len(&bins.dataset("start").map_err(|error| {
        generation_error(format!("generated level is missing bins/start: {error}"))
    })?)?;
    if multiplicative_weights.len() != bin_count {
        return Err(generation_error(format!(
            "{} normalization has {} weights for {bin_count} bins",
            normalization.as_str(),
            multiplicative_weights.len()
        )));
    }

    let stored = stored_normalization_weights(normalization, multiplicative_weights);
    if bins.link_exists(spec.name) {
        bins.unlink(spec.name).map_err(|error| {
            generation_error(format!(
                "failed to replace bins/{} normalization column: {error}",
                spec.name
            ))
        })?;
    }
    let dataset = bins
        .new_dataset_builder()
        .with_data(stored.as_slice())
        .shuffle()
        .deflate(compression_level)
        .create(spec.name)
        .map_err(|error| {
            generation_error(format!(
                "failed to write bins/{} normalization column: {error}",
                spec.name
            ))
        })?;
    dataset
        .new_attr::<bool>()
        .shape(())
        .create("divisive_weights")
        .and_then(|attribute| attribute.write_scalar(&spec.divisive))
        .map_err(|error| {
            generation_error(format!(
                "failed to mark bins/{} weight convention: {error}",
                spec.name
            ))
        })?;
    let normalization_label = normalization
        .as_str()
        .parse::<VarLenUnicode>()
        .map_err(|error| generation_error(format!("invalid normalization label: {error}")))?;
    dataset
        .new_attr::<VarLenUnicode>()
        .shape(())
        .create("cool2mcool_normalization")
        .and_then(|attribute| attribute.write_scalar(&normalization_label))
        .map_err(|error| {
            generation_error(format!(
                "failed to annotate bins/{} normalization column: {error}",
                spec.name
            ))
        })?;
    let scope = normalization_scope(normalization)
        .parse::<VarLenUnicode>()
        .map_err(|error| generation_error(format!("invalid normalization scope: {error}")))?;
    dataset
        .new_attr::<VarLenUnicode>()
        .shape(())
        .create("cool2mcool_scope")
        .and_then(|attribute| attribute.write_scalar(&scope))
        .map_err(|error| {
            generation_error(format!(
                "failed to annotate bins/{} normalization scope: {error}",
                spec.name
            ))
        })?;
    dataset
        .new_attr::<u32>()
        .shape(())
        .create("cool2mcool_normalization_version")
        .and_then(|attribute| attribute.write_scalar(&NORMALIZATION_VERSION))
        .map_err(|error| {
            generation_error(format!(
                "failed to annotate bins/{} normalization version: {error}",
                spec.name
            ))
        })?;
    Ok(())
}

fn remove_normalization_column(level: &Group, normalization: Normalization) -> Result<()> {
    let spec = normalization_column_spec(normalization);
    let bins = level.group("bins").map_err(|error| {
        generation_error(format!("generated level is missing bins group: {error}"))
    })?;
    if bins.link_exists(spec.name) {
        bins.unlink(spec.name).map_err(|error| {
            generation_error(format!(
                "failed to remove bins/{} normalization column: {error}",
                spec.name
            ))
        })?;
    }
    Ok(())
}

fn stored_normalization_weights(
    normalization: Normalization,
    multiplicative_weights: &[f64],
) -> Vec<f64> {
    let spec = normalization_column_spec(normalization);
    multiplicative_weights
        .iter()
        .map(|weight| {
            if !weight.is_finite() || *weight <= 0.0 {
                f64::NAN
            } else if spec.divisive {
                1.0 / *weight
            } else {
                *weight
            }
        })
        .collect()
}

fn normalization_column_spec(normalization: Normalization) -> NormalizationColumnSpec {
    match normalization {
        Normalization::Ice => NormalizationColumnSpec {
            name: "weight",
            divisive: false,
        },
        Normalization::Kr => NormalizationColumnSpec {
            name: "KR",
            divisive: true,
        },
        Normalization::Vc => NormalizationColumnSpec {
            name: "VC",
            divisive: true,
        },
        Normalization::VcSqrt => NormalizationColumnSpec {
            name: "VC_SQRT",
            divisive: true,
        },
        Normalization::Raw => panic!("raw contacts do not have a stored normalization column"),
    }
}

fn normalization_scope(normalization: Normalization) -> &'static str {
    match normalization {
        Normalization::Ice | Normalization::Kr => "whole-assembly",
        Normalization::Vc | Normalization::VcSqrt => "chromosome-cis",
        Normalization::Raw => "raw",
    }
}

fn validate_stored_normalizations(
    level: &Group,
    resolution: u64,
    expected_normalizations: &[Normalization],
) -> Result<()> {
    let bins = level.group("bins").map_err(|error| {
        generation_error(format!(
            "resolution {resolution} is missing bins after normalization: {error}"
        ))
    })?;
    let bin_count = dataset_len(&bins.dataset("start").map_err(|error| {
        generation_error(format!(
            "resolution {resolution} is missing bins/start after normalization: {error}"
        ))
    })?)?;
    for normalization in STORED_NORMALIZATIONS_WITH_KR {
        let spec = normalization_column_spec(normalization);
        if !expected_normalizations.contains(&normalization) {
            if bins.link_exists(spec.name) {
                return Err(generation_error(format!(
                    "resolution {resolution} unexpectedly contains bins/{}",
                    spec.name
                )));
            }
            continue;
        }
        let dataset = bins.dataset(spec.name).map_err(|error| {
            generation_error(format!(
                "resolution {resolution} is missing bins/{} after normalization: {error}",
                spec.name
            ))
        })?;
        let observed_len = dataset_len(&dataset)?;
        if observed_len != bin_count {
            return Err(generation_error(format!(
                "resolution {resolution} bins/{} has {observed_len} values for {bin_count} bins",
                spec.name
            )));
        }
        let divisive = dataset
            .attr("divisive_weights")
            .and_then(|attribute| attribute.read_scalar::<bool>())
            .map_err(|error| {
                generation_error(format!(
                    "resolution {resolution} bins/{} is missing its weight convention: {error}",
                    spec.name
                ))
            })?;
        if divisive != spec.divisive {
            return Err(generation_error(format!(
                "resolution {resolution} bins/{} has the wrong weight convention",
                spec.name
            )));
        }
        let scope = dataset
            .attr("cool2mcool_scope")
            .and_then(|attribute| attribute.read_scalar::<VarLenUnicode>())
            .map_err(|error| {
                generation_error(format!(
                    "resolution {resolution} bins/{} is missing its normalization scope: {error}",
                    spec.name
                ))
            })?;
        if scope.as_str() != normalization_scope(normalization) {
            return Err(generation_error(format!(
                "resolution {resolution} bins/{} declares unexpected scope {:?}",
                spec.name,
                scope.as_str(),
            )));
        }
    }
    Ok(())
}

fn normalization_manifest(normalizations: &[Normalization]) -> Result<VarLenUnicode> {
    normalizations
        .iter()
        .map(|normalization| normalization.as_str())
        .collect::<Vec<_>>()
        .join(",")
        .parse::<VarLenUnicode>()
        .map_err(|error| generation_error(format!("invalid normalization manifest: {error}")))
}

fn write_level_normalization_manifest(
    level: &Group,
    normalizations: &[Normalization],
) -> Result<()> {
    let manifest = normalization_manifest(normalizations)?;
    level
        .new_attr::<VarLenUnicode>()
        .shape(())
        .create("cool2mcool_normalizations")
        .and_then(|attribute| attribute.write_scalar(&manifest))
        .map_err(|error| {
            generation_error(format!(
                "failed to write level cool2mcool_normalizations manifest: {error}"
            ))
        })
}

fn write_generation_manifest(
    file: &File,
    resolutions: &[u64],
    kr_min_resolution: u64,
) -> Result<()> {
    let has_kr = resolutions
        .iter()
        .any(|resolution| *resolution >= kr_min_resolution);
    let normalizations = normalization_manifest(stored_normalizations_for_kr(has_kr))?;
    file.new_attr::<VarLenUnicode>()
        .shape(())
        .create("cool2mcool_normalizations")
        .and_then(|attribute| attribute.write_scalar(&normalizations))
        .map_err(|error| {
            generation_error(format!(
                "failed to write cool2mcool_normalizations manifest: {error}"
            ))
        })?;
    file.new_attr::<u64>()
        .shape(())
        .create("cool2mcool_kr_min_resolution")
        .and_then(|attribute| attribute.write_scalar(&kr_min_resolution))
        .map_err(|error| {
            generation_error(format!(
                "failed to write cool2mcool KR minimum resolution: {error}"
            ))
        })?;
    file.new_attr::<u32>()
        .shape(())
        .create("cool2mcool_normalization_version")
        .and_then(|attribute| attribute.write_scalar(&NORMALIZATION_VERSION))
        .map_err(|error| {
            generation_error(format!(
                "failed to write cool2mcool normalization version: {error}"
            ))
        })?;
    if has_kr {
        let kr_algorithm = KR_ALGORITHM
            .parse::<VarLenUnicode>()
            .map_err(|error| generation_error(format!("invalid KR algorithm manifest: {error}")))?;
        file.new_attr::<VarLenUnicode>()
            .shape(())
            .create("cool2mcool_kr_algorithm")
            .and_then(|attribute| attribute.write_scalar(&kr_algorithm))
            .map_err(|error| {
                generation_error(format!(
                    "failed to write cool2mcool KR algorithm manifest: {error}"
                ))
            })?;
    }
    Ok(())
}

fn matching_table_lengths(location: &Group, label: &str, paths: &[&str]) -> Result<usize> {
    let mut expected = None;
    for path in paths {
        let dataset = location
            .dataset(path)
            .map_err(|error| generation_error(format!("{label} is missing {path}: {error}")))?;
        let length = dataset_len(&dataset)?;
        match expected {
            Some(expected) if expected != length => {
                return Err(generation_error(format!(
                    "{label} columns have different lengths: expected {expected}, {path} has {length}"
                )));
            }
            None => expected = Some(length),
            _ => {}
        }
    }
    Ok(expected.unwrap_or(0))
}

fn dataset_len(dataset: &Dataset) -> Result<usize> {
    let shape = dataset.shape();
    if shape.len() != 1 {
        return Err(generation_error(format!(
            "dataset {} must be one-dimensional, found shape {shape:?}",
            dataset.name()
        )));
    }
    Ok(shape[0])
}

fn read_u64_dataset(dataset: &Dataset) -> Result<Vec<u64>> {
    if let Ok(values) = dataset.read_1d::<u64>() {
        return Ok(values.to_vec());
    }
    if let Ok(values) = dataset.read_1d::<u32>() {
        return Ok(values.iter().map(|value| *value as u64).collect());
    }
    if let Ok(values) = dataset.read_1d::<i64>() {
        return values
            .iter()
            .map(|value| {
                u64::try_from(*value).map_err(|_| {
                    generation_error(format!(
                        "dataset {} contains negative value {value}",
                        dataset.name()
                    ))
                })
            })
            .collect();
    }
    let values = dataset.read_1d::<i32>().map_err(|error| {
        generation_error(format!(
            "dataset {} is not a supported integer type: {error}",
            dataset.name()
        ))
    })?;
    values
        .iter()
        .map(|value| {
            u64::try_from(*value).map_err(|_| {
                generation_error(format!(
                    "dataset {} contains negative value {value}",
                    dataset.name()
                ))
            })
        })
        .collect()
}

fn read_u64_dataset_slice(dataset: &Dataset, range: std::ops::Range<usize>) -> Result<Vec<u64>> {
    if let Ok(values) = dataset.read_slice_1d::<u64, _>(range.clone()) {
        return Ok(values.to_vec());
    }
    if let Ok(values) = dataset.read_slice_1d::<u32, _>(range.clone()) {
        return Ok(values.iter().map(|value| *value as u64).collect());
    }
    if let Ok(values) = dataset.read_slice_1d::<i64, _>(range.clone()) {
        return values
            .iter()
            .map(|value| {
                u64::try_from(*value).map_err(|_| {
                    generation_error(format!(
                        "dataset {} contains negative value {value}",
                        dataset.name()
                    ))
                })
            })
            .collect();
    }
    let values = dataset.read_slice_1d::<i32, _>(range).map_err(|error| {
        generation_error(format!(
            "dataset {} is not a supported integer type: {error}",
            dataset.name()
        ))
    })?;
    values
        .iter()
        .map(|value| {
            u64::try_from(*value).map_err(|_| {
                generation_error(format!(
                    "dataset {} contains negative value {value}",
                    dataset.name()
                ))
            })
        })
        .collect()
}

fn read_f64_dataset_slice(dataset: &Dataset, range: std::ops::Range<usize>) -> Result<Vec<f64>> {
    if let Ok(values) = dataset.read_slice_1d::<f64, _>(range.clone()) {
        return Ok(values.to_vec());
    }
    if let Ok(values) = dataset.read_slice_1d::<f32, _>(range.clone()) {
        return Ok(values.iter().map(|value| *value as f64).collect());
    }
    if let Ok(values) = dataset.read_slice_1d::<i64, _>(range.clone()) {
        return Ok(values.iter().map(|value| *value as f64).collect());
    }
    if let Ok(values) = dataset.read_slice_1d::<i32, _>(range.clone()) {
        return Ok(values.iter().map(|value| *value as f64).collect());
    }
    if let Ok(values) = dataset.read_slice_1d::<u64, _>(range.clone()) {
        return Ok(values.iter().map(|value| *value as f64).collect());
    }
    let values = dataset.read_slice_1d::<u32, _>(range).map_err(|error| {
        generation_error(format!(
            "dataset {} is not a supported numeric type: {error}",
            dataset.name()
        ))
    })?;
    Ok(values.iter().map(|value| *value as f64).collect())
}

fn required_string_attr(location: &Location, name: &str) -> Result<String> {
    optional_string_attr(location, name)?
        .ok_or_else(|| generation_error(format!("missing required {name} attribute")))
}

fn optional_string_attr(location: &Location, name: &str) -> Result<Option<String>> {
    let attribute = match location.attr(name) {
        Ok(attribute) => attribute,
        Err(_) => return Ok(None),
    };
    if let Ok(value) = attribute.read_scalar::<VarLenUnicode>() {
        return Ok(Some(value.as_str().to_string()));
    }
    if let Ok(value) = attribute.read_scalar::<VarLenAscii>() {
        return Ok(Some(value.as_str().to_string()));
    }
    Err(generation_error(format!(
        "attribute {name} on {} is not a variable-length string",
        location.name()
    )))
}

fn required_u64_attr(location: &Location, name: &str) -> Result<u64> {
    let attribute = location
        .attr(name)
        .map_err(|error| generation_error(format!("missing required {name} attribute: {error}")))?;
    if let Ok(value) = attribute.read_scalar::<u64>() {
        return Ok(value);
    }
    if let Ok(value) = attribute.read_scalar::<u32>() {
        return Ok(value as u64);
    }
    if let Ok(value) = attribute.read_scalar::<i64>() {
        return u64::try_from(value)
            .map_err(|_| generation_error(format!("attribute {name} cannot be negative")));
    }
    let value = attribute.read_scalar::<i32>().map_err(|error| {
        generation_error(format!(
            "attribute {name} on {} is not a supported integer: {error}",
            location.name()
        ))
    })?;
    u64::try_from(value)
        .map_err(|_| generation_error(format!("attribute {name} cannot be negative")))
}

fn sync_completed_partial(partial: &Path) -> Result<()> {
    fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(partial)
        .and_then(|file| file.sync_all())
        .map_err(|error| {
            generation_error(format!(
                "failed to synchronize completed partial output {}: {error}",
                partial.display()
            ))
        })
}

#[cfg(unix)]
fn apply_input_file_permissions(input: &Path, output: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;

    let input_mode = fs::metadata(input)
        .map_err(|error| {
            generation_error(format!(
                "failed to read input permissions from {}: {error}",
                input.display()
            ))
        })?
        .permissions()
        .mode();
    let mut output_permissions = fs::metadata(output)
        .map_err(|error| {
            generation_error(format!(
                "failed to read output permissions from {}: {error}",
                output.display()
            ))
        })?
        .permissions();
    output_permissions.set_mode(input_mode & 0o666);
    fs::set_permissions(output, output_permissions).map_err(|error| {
        generation_error(format!(
            "failed to apply input permissions to {}: {error}",
            output.display()
        ))
    })
}

#[cfg(not(unix))]
fn apply_input_file_permissions(_input: &Path, _output: &Path) -> Result<()> {
    Ok(())
}

fn install_partial_output(partial: TempPath, output: &Path, force: bool) -> Result<()> {
    let partial_display = partial.display().to_string();
    let result = if force {
        partial.persist(output)
    } else {
        partial.persist_noclobber(output)
    };
    result.map_err(|error| {
        let operation = if force {
            "atomically replace"
        } else {
            "install without replacing"
        };
        generation_error(format!(
            "failed to {operation} {} with {}: {}",
            output.display(),
            partial_display,
            error.error
        ))
    })
}

fn partial_output_path(output: &Path) -> Result<TempPath> {
    tempfile::Builder::new()
        .prefix(".cool2mcool-partial-")
        .suffix(".mcool")
        .tempfile_in(parent_directory(output))
        .map(|file| file.into_temp_path())
        .map_err(|error| {
            generation_error(format!(
                "could not create a partial output beside {}: {error}",
                output.display()
            ))
        })
}

fn generation_error(message: impl Into<String>) -> Error {
    Error::message(format!("cool2mcool generation error: {}", message.into()))
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::{Path, PathBuf},
        sync::atomic::{AtomicU64, Ordering},
    };

    use hdf5::{
        filters::Filter,
        types::{FixedAscii, VarLenUnicode},
        File, Location,
    };

    use super::{
        annotate_normalization_metric, apply_input_file_permissions, install_partial_output,
        normalization_column_spec, partial_output_path, remove_normalization_column,
        runtime_normalization_memory_budget_bytes, stored_normalization_weights,
        stored_normalizations_for_resolution, validate_fixed_1k_input, validate_kr_min_resolution,
        validate_resolution_ladder, validate_stored_normalizations, write_generation_manifest,
        write_level_normalization_manifest, write_normalization_column, Normalization, TempPath,
        BASE_RESOLUTION, DEFAULT_COMPRESSION_LEVEL, DEFAULT_RESOLUTIONS, KR_ALGORITHM,
        NORMALIZATION_VERSION,
    };

    static NEXT_TEST_ID: AtomicU64 = AtomicU64::new(1);

    #[test]
    fn normalization_budget_is_eighty_percent_of_available_memory() {
        assert_eq!(runtime_normalization_memory_budget_bytes(1_000), 800);
        assert_eq!(runtime_normalization_memory_budget_bytes(9), 7);
    }

    #[cfg(unix)]
    #[test]
    fn generated_output_inherits_the_input_file_mode() {
        use std::os::unix::fs::PermissionsExt;

        let input = TestFile::new("input-permissions", "cool");
        let output = TestFile::new("output-permissions", "mcool");
        fs::write(input.path(), b"input").expect("write input");
        fs::write(output.path(), b"output").expect("write output");
        fs::set_permissions(input.path(), fs::Permissions::from_mode(0o640))
            .expect("set input permissions");
        fs::set_permissions(output.path(), fs::Permissions::from_mode(0o600))
            .expect("set output permissions");

        apply_input_file_permissions(input.path(), output.path()).expect("copy input permissions");

        let mode = fs::metadata(output.path())
            .expect("output metadata")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o640);
    }

    struct TestFile {
        path: PathBuf,
    }

    impl TestFile {
        fn new(label: &str, extension: &str) -> Self {
            let id = NEXT_TEST_ID.fetch_add(1, Ordering::Relaxed);
            Self {
                path: std::env::temp_dir().join(format!(
                    "cool2mcool-{label}-{}-{id}.{extension}",
                    std::process::id()
                )),
            }
        }

        fn path(&self) -> &Path {
            &self.path
        }
    }

    impl Drop for TestFile {
        fn drop(&mut self) {
            let _ = fs::remove_file(&self.path);
        }
    }

    fn write_string_attr(location: &Location, name: &str, value: &str) {
        let value = value
            .parse::<VarLenUnicode>()
            .expect("valid test attribute");
        location
            .new_attr::<VarLenUnicode>()
            .shape(())
            .create(name)
            .and_then(|attribute| attribute.write_scalar(&value))
            .expect("write string attribute");
    }

    fn create_valid_input(path: &Path, bin_size: u64, storage_mode: &str) {
        let file = File::create(path).expect("create test cool");
        write_string_attr(&file, "format", "HDF5::Cooler");
        write_string_attr(&file, "bin-type", "fixed");
        write_string_attr(&file, "storage-mode", storage_mode);
        file.new_attr::<u64>()
            .shape(())
            .create("bin-size")
            .and_then(|attribute| attribute.write_scalar(&bin_size))
            .expect("write bin-size");

        file.create_group("chroms").expect("create chroms");
        file.create_group("bins").expect("create bins");
        file.create_group("pixels").expect("create pixels");
        file.create_group("indexes").expect("create indexes");
        let names = [FixedAscii::<4>::from_ascii("chr1").expect("fixed ASCII")];
        file.new_dataset_builder()
            .with_data(&names)
            .create("chroms/name")
            .expect("write chrom names");
        file.new_dataset_builder()
            .with_data(&[2_000_u64])
            .create("chroms/length")
            .expect("write chrom lengths");
        file.new_dataset_builder()
            .with_data(&[0_i32, 0])
            .create("bins/chrom")
            .expect("write bin chroms");
        file.new_dataset_builder()
            .with_data(&[0_u64, 1_000])
            .create("bins/start")
            .expect("write bin starts");
        file.new_dataset_builder()
            .with_data(&[1_000_u64, 2_000])
            .create("bins/end")
            .expect("write bin ends");
        file.new_dataset_builder()
            .with_data(&[0_u64, 0, 1])
            .create("pixels/bin1_id")
            .expect("write pixel bin1");
        file.new_dataset_builder()
            .with_data(&[0_u64, 1, 1])
            .create("pixels/bin2_id")
            .expect("write pixel bin2");
        file.new_dataset_builder()
            .with_data(&[4_i32, 2, 3])
            .create("pixels/count")
            .expect("write pixel counts");
        file.new_dataset_builder()
            .with_data(&[0_u64, 2, 3])
            .create("indexes/bin1_offset")
            .expect("write bin offsets");
        file.new_dataset_builder()
            .with_data(&[0_u64, 2])
            .create("indexes/chrom_offset")
            .expect("write chrom offsets");
    }

    #[test]
    fn default_and_custom_resolution_ladders_are_valid() {
        validate_resolution_ladder(DEFAULT_RESOLUTIONS).expect("default ladder");
        validate_resolution_ladder(&[1_000, 2_000, 7_000])
            .expect("custom ladder need not contain every default level");
        validate_resolution_ladder(&[5_000, 10_000])
            .expect("custom ladder may omit the 1 kb input level");

        assert!(validate_resolution_ladder(&[]).is_err());
        assert!(validate_resolution_ladder(&[1_000, 1_500]).is_err());
        assert!(validate_resolution_ladder(&[1_000, 5_000, 5_000]).is_err());
        assert!(validate_resolution_ladder(&[1_000, 5_000, 2_000]).is_err());
        assert_eq!(
            DEFAULT_RESOLUTIONS,
            &[
                BASE_RESOLUTION,
                5_000,
                10_000,
                25_000,
                50_000,
                100_000,
                250_000,
                500_000,
                1_000_000,
                2_500_000,
            ]
        );
    }

    #[test]
    fn kr_minimum_resolution_selects_only_eligible_levels() {
        validate_kr_min_resolution(BASE_RESOLUTION).expect("default threshold");
        validate_kr_min_resolution(5_000).expect("5 kb threshold");
        assert!(validate_kr_min_resolution(0).is_err());
        assert!(validate_kr_min_resolution(1_500).is_err());

        assert!(!stored_normalizations_for_resolution(1_000, 5_000).contains(&Normalization::Kr));
        assert!(stored_normalizations_for_resolution(5_000, 5_000).contains(&Normalization::Kr));
    }

    #[test]
    fn output_installation_never_clobbers_without_force() {
        let partial = TestFile::new("partial-no-force", "mcool");
        let output = TestFile::new("output-no-force", "mcool");
        fs::write(partial.path(), b"new").expect("write partial output");
        fs::write(output.path(), b"old").expect("write existing output");

        let partial_path = TempPath::try_from_path(partial.path().to_path_buf())
            .expect("manage partial output path");
        let error = install_partial_output(partial_path, output.path(), false)
            .expect_err("no-force installation must reject a raced destination");

        assert!(error.to_string().contains("without replacing"));
        assert_eq!(fs::read(output.path()).expect("read output"), b"old");
        assert!(!partial.path().exists());
    }

    #[test]
    fn partial_outputs_are_exclusively_created_beside_the_destination() {
        let output = TestFile::new("reserved-output", "mcool");
        let first = partial_output_path(output.path()).expect("reserve first partial");
        let second = partial_output_path(output.path()).expect("reserve second partial");

        assert!(first.is_file());
        assert!(second.is_file());
        assert_ne!(first.to_path_buf(), second.to_path_buf());
        assert_eq!(first.parent(), output.path().parent());
        assert_eq!(second.parent(), output.path().parent());
    }

    #[test]
    fn forced_output_installation_atomically_replaces_existing_file() {
        let partial = TestFile::new("partial-force", "mcool");
        let output = TestFile::new("output-force", "mcool");
        fs::write(partial.path(), b"new").expect("write partial output");
        fs::write(output.path(), b"old").expect("write existing output");

        let partial_path = TempPath::try_from_path(partial.path().to_path_buf())
            .expect("manage partial output path");
        install_partial_output(partial_path, output.path(), true).expect("forced install");

        assert_eq!(fs::read(output.path()).expect("read output"), b"new");
        assert!(!partial.path().exists());
    }

    #[test]
    fn validates_fixed_symmetric_upper_1k_input() {
        let valid = TestFile::new("valid", "cool");
        create_valid_input(valid.path(), 1_000, "symmetric-upper");
        let summary = validate_fixed_1k_input(valid.path()).expect("valid 1 kb cool");
        assert_eq!(summary.bins, 2);
        assert_eq!(summary.pixels, 3);

        let wrong_resolution = TestFile::new("wrong-resolution", "cool");
        create_valid_input(wrong_resolution.path(), 5_000, "symmetric-upper");
        assert!(validate_fixed_1k_input(wrong_resolution.path())
            .expect_err("5 kb input should fail")
            .to_string()
            .contains("bin-size must be 1000"));

        let square = TestFile::new("square", "cool");
        create_valid_input(square.path(), 1_000, "square");
        assert!(validate_fixed_1k_input(square.path())
            .expect_err("square storage should fail")
            .to_string()
            .contains("storage-mode must be symmetric-upper"));
    }

    #[test]
    fn converts_multiplicative_weights_to_declared_storage_conventions() {
        let source = [2.0, 4.0, f64::NAN, 0.0];
        let ice = stored_normalization_weights(Normalization::Ice, &source);
        assert_eq!(ice[0..2], [2.0, 4.0]);
        assert!(ice[2].is_nan());
        assert!(ice[3].is_nan());

        for normalization in [Normalization::Kr, Normalization::Vc, Normalization::VcSqrt] {
            let stored = stored_normalization_weights(normalization, &source);
            assert_eq!(stored[0..2], [0.5, 0.25]);
            assert!(stored[2].is_nan());
            assert!(stored[3].is_nan());
            assert!(normalization_column_spec(normalization).divisive);
        }
        assert!(!normalization_column_spec(Normalization::Ice).divisive);
    }

    #[test]
    fn writes_normalization_columns_and_cool2mcool_metadata() {
        let test_file = TestFile::new("columns", "h5");
        let file = File::create(test_file.path()).expect("create test HDF5");
        let level = file.create_group("level").expect("create level");
        let bins = level.create_group("bins").expect("create bins");
        bins.new_dataset_builder()
            .with_data(&[0_u64, 1_000])
            .create("start")
            .expect("write starts");
        let weights = [2.0, 4.0];

        for normalization in STORED_NORMALIZATIONS_FOR_TEST {
            let compression_level = if normalization == Normalization::Ice {
                6
            } else {
                DEFAULT_COMPRESSION_LEVEL
            };
            write_normalization_column(&level, normalization, &weights, compression_level)
                .expect("write normalization");
            let spec = normalization_column_spec(normalization);
            let dataset = bins.dataset(spec.name).expect("stored column");
            assert_eq!(
                dataset.filters(),
                vec![Filter::Shuffle, Filter::Deflate(compression_level)]
            );
            let stored = dataset.read_1d::<f64>().expect("read weights").to_vec();
            let expected = if spec.divisive {
                vec![0.5, 0.25]
            } else {
                weights.to_vec()
            };
            assert_eq!(stored, expected);
            assert_eq!(
                dataset
                    .attr("divisive_weights")
                    .expect("convention attr")
                    .read_scalar::<bool>()
                    .expect("bool convention"),
                spec.divisive
            );
            assert_eq!(
                dataset
                    .attr("cool2mcool_normalization")
                    .expect("normalization label")
                    .read_scalar::<VarLenUnicode>()
                    .expect("string normalization label")
                    .as_str(),
                normalization.as_str()
            );
            assert_eq!(
                dataset
                    .attr("cool2mcool_scope")
                    .expect("normalization scope")
                    .read_scalar::<VarLenUnicode>()
                    .expect("string normalization scope")
                    .as_str(),
                super::normalization_scope(normalization)
            );
            assert_eq!(
                dataset
                    .attr("cool2mcool_normalization_version")
                    .expect("normalization version")
                    .read_scalar::<u32>()
                    .expect("dataset version"),
                NORMALIZATION_VERSION
            );
        }

        annotate_normalization_metric(
            &level,
            Normalization::Kr,
            "cool2mcool_coverage_percentile",
            15.0,
        )
        .expect("annotate KR percentile");
        assert_eq!(
            bins.dataset("KR")
                .expect("KR column")
                .attr("cool2mcool_coverage_percentile")
                .expect("KR percentile attr")
                .read_scalar::<f64>()
                .expect("KR percentile"),
            15.0,
        );

        write_level_normalization_manifest(&level, &STORED_NORMALIZATIONS_FOR_TEST)
            .expect("write level manifest");
        validate_stored_normalizations(&level, 1_000, &STORED_NORMALIZATIONS_FOR_TEST)
            .expect("all normalization columns validate");
        assert_eq!(
            level
                .attr("cool2mcool_normalizations")
                .expect("level normalization manifest")
                .read_scalar::<VarLenUnicode>()
                .expect("level manifest string")
                .as_str(),
            "ice,kr,vc,vc_sqrt"
        );

        write_generation_manifest(&file, &[1_000], BASE_RESOLUTION).expect("write manifest");
        assert_eq!(
            file.attr("cool2mcool_normalization_version")
                .expect("version attr")
                .read_scalar::<u32>()
                .expect("version"),
            NORMALIZATION_VERSION
        );
        assert_eq!(
            file.attr("cool2mcool_kr_min_resolution")
                .expect("KR minimum resolution")
                .read_scalar::<u64>()
                .expect("KR minimum resolution value"),
            BASE_RESOLUTION
        );
        assert_eq!(
            file.attr("cool2mcool_kr_algorithm")
                .expect("KR algorithm attr")
                .read_scalar::<VarLenUnicode>()
                .expect("KR algorithm")
                .as_str(),
            KR_ALGORITHM
        );
    }

    #[test]
    fn skipped_kr_is_absent_and_manifests_remain_truthful() {
        let test_file = TestFile::new("columns-without-kr", "h5");
        let file = File::create(test_file.path()).expect("create test HDF5");
        let level = file.create_group("level").expect("create level");
        let bins = level.create_group("bins").expect("create bins");
        bins.new_dataset_builder()
            .with_data(&[0_u64, 1_000])
            .create("start")
            .expect("write starts");
        let weights = [2.0, 4.0];
        let expected = stored_normalizations_for_resolution(1_000, 5_000);

        for normalization in expected {
            write_normalization_column(&level, *normalization, &weights, DEFAULT_COMPRESSION_LEVEL)
                .expect("write selected normalization");
        }
        write_normalization_column(
            &level,
            Normalization::Kr,
            &weights,
            DEFAULT_COMPRESSION_LEVEL,
        )
        .expect("write inherited KR fixture");
        remove_normalization_column(&level, Normalization::Kr).expect("remove skipped KR");
        write_level_normalization_manifest(&level, expected).expect("write level manifest");
        validate_stored_normalizations(&level, 1_000, expected)
            .expect("selected normalization columns validate");

        assert!(!bins.link_exists("KR"));
        assert_eq!(
            level
                .attr("cool2mcool_normalizations")
                .expect("level normalization manifest")
                .read_scalar::<VarLenUnicode>()
                .expect("level manifest string")
                .as_str(),
            "ice,vc,vc_sqrt"
        );

        write_generation_manifest(&file, &[1_000], 5_000).expect("write file manifest");
        assert_eq!(
            file.attr("cool2mcool_normalizations")
                .expect("file normalization manifest")
                .read_scalar::<VarLenUnicode>()
                .expect("file manifest string")
                .as_str(),
            "ice,vc,vc_sqrt"
        );
        assert!(file.attr("cool2mcool_kr_algorithm").is_err());
    }

    const STORED_NORMALIZATIONS_FOR_TEST: [Normalization; 4] = [
        Normalization::Ice,
        Normalization::Kr,
        Normalization::Vc,
        Normalization::VcSqrt,
    ];
}
