use std::ffi::OsString;
use std::path::PathBuf;

use clap::{arg, Arg, ArgAction, Command, 
            Subcommand, value_parser, ColorChoice};

const VERSION: &str = "0.2.1";

pub fn cli() -> Command {
    Command::new("cphasing")
        .color(ColorChoice::Auto)
        .about("Phasing and scaffolding based on Pore-C or Hi-C data")
        .subcommand_required(true)
        .version(VERSION)
        .arg_required_else_help(true)
        .allow_external_subcommands(true)
        .subcommand(
            Command::new("aligner")
                .hide(true)
                .about("align methylation reads")
                .arg(arg!(<FASTA> "fasta"))
                .arg(arg!(<BAM> "align bam from `dorado`"))
                .arg(
                    Arg::new("MIN_QUALITY")
                        .long("min-quality")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("10"))
                .arg(
                    Arg::new("MIN_PROB")
                        .long("min-prob")
                        .short('p')
                        .value_parser(value_parser!(f32))
                        .default_value("0.75"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        ).subcommand(
            Command::new("realign")
                .hide(true)
                .about("rescue secondary alignment by high-quality alignments")
                .arg(arg!(<PAF> "paf from minimap2 with secondary"))
                .arg(
                    Arg::new("MIN_MAPQ")
                        .long("min-mapq")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("1"))
                .arg(
                    Arg::new("FORMAT")
                        .long("format")
                        .short('f')
                        .value_parser(value_parser!(String))
                        .default_value("paf")
                        .help("input format")
                        )
                .arg(
                    Arg::new("CONTACTS")
                        .long("contacts")
                        .short('c')
                        .value_parser(value_parser!(String))
                        .default_value("none")
                        .help("contacts file for pore-c or hi-c data")
                )
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8")
                )
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),

        )
        .subcommand(
            Command::new("methalign")
                     .about("refine alignments by methylation or without methylation")
                        .arg(arg!(<BAM> "align bam from `dorado` "))
                        .arg(
                            Arg::new("FASTA")
                                .long("fasta")
                                .short('f')
                                .value_parser(value_parser!(String))
                                .default_value("none")
                                .help("fasta file for reference, if not set, only use sequence matching"))
                        .arg(
                            Arg::new("BEDGRAPH")
                                .long("bed")
                                .short('b')
                                .value_parser(value_parser!(String))
                                .default_value("none")
                                .help("bed file for regions to refine, if not set, use whole genome"))
                        .arg(
                            Arg::new("MATCH_SCORE")
                                .long("match-score")
                                .short('A')
                                .value_parser(value_parser!(i32))
                                .default_value("0")
                                .help("match score of methylation sites")
                        )
                        .arg(
                            Arg::new("REF_PENALTY")
                                .long("ref-penalty")
                                .value_parser(value_parser!(i32))
                                .default_value("2")
                                .help("penalty for mismatch methylation on reference")
                            )
                        .arg(
                            Arg::new("READ_PENALTY")
                                .long("read-penalty")
                                .value_parser(value_parser!(i32))
                                .default_value("2")
                                .help("penalty for mismatch methylation on read")
                            )
                        .arg(
                            Arg::new("REF_PROB_CUTOFF")
                                .long("ref-prob-cutoff")
                                .short('r')
                                .value_parser(value_parser!(f64))
                                .default_value("50.0")
                                .help("cutoff of probability for reference methylation, 0-100"))
                        .arg(
                            Arg::new("PROB_CUTOFF")
                                .long("prob-cutoff")
                                .short('c')
                                .value_parser(value_parser!(u8))
                                .default_value("128")
                                .help("cutoff of probability for read methylation, 0-255"))
                        .arg(
                            Arg::new("DESIGNATE_MAPQ")
                                .long("designate-mapq")
                                .short('q')
                                .value_parser(value_parser!(u8))
                                .default_value("2")
                                .help("designate mapq for refined alignments"))
                        .arg(
                            Arg::new("IS_SET_Y")
                                .long("is-set-y")
                                .short('y')
                                .action(ArgAction::SetTrue)
                                .default_value("false")
                                .help("the aligner was set -Y for supplementary alignments")
                        )
                        .arg(
                            Arg::new("CPG")
                                .long("cpg")
                                .action(ArgAction::SetTrue)
                                .default_value("false")
                                .help("use cpg methylation only, default use all 5mC sites")
                        )
                        .arg(
                            Arg::new("OUTPUT_SECONDARY")
                                .long("output-secondary")
                                .short('s')
                                .action(ArgAction::SetTrue)
                                .default_value("false")
                                .help("output secondary alignments")
                        )
                        .arg(
                            Arg::new("THREADS")
                                .long("threads")
                                .short('t')
                                .value_parser(value_parser!(usize))
                                .default_value("8"))
                        .arg(
                            Arg::new("OUTPUT")
                                .long("output")
                                .short('o')
                                .value_parser(value_parser!(String))
                                .default_value("-")
                                .help("output file, default is stdout"))
        )
        .subcommand(
            Command::new("alleles")
                .alias("allele")
                .hide(true)
                .about("Identify the allelic contig pairs by self comparison (unstable and slowly)")
                .arg(arg!(<FASTA> "fasta"))
                .arg(
                    Arg::new("K")
                        .long("kmer-size")
                        .short('k')
                        .value_parser(value_parser!(usize))
                        .default_value("19"))
                .arg(
                    Arg::new("W")
                        .long("window-size")
                        .short('w')
                        .value_parser(value_parser!(usize))
                        .default_value("19"))
                .arg(
                    Arg::new("M")
                        .long("minimum-similarity")
                        .short('m')
                        .value_parser(value_parser!(f64))
                        .default_value("0.85"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("kprune")
                .about("Identify the allelic and cross-allelic contig pairs by allele table")
                .arg(arg!(<ALLELETABLE> "allele table"))
                .arg(arg!(<CONTACTS> "contacts"))
                .arg(arg!(<PRUNETABLE> "output path of prune table"))
                .arg(
                    Arg::new("COUNTRE")
                        .long("count-re")
                        .short('c')
                        .value_parser(value_parser!(String))
                        .default_value("none")
                        .help("restriction enzyme count file")
                )
                .arg(
                    Arg::new("METHOD")
                        .long("method")
                        .short('m')
                        .value_parser(value_parser!(String))
                        .default_value("precise")
                        .help("method of prune: [fast, precise, greedy]")
                        )
                .arg(
                    Arg::new("NORMALIZATION_METHOD")
                        .long("normalization-method")
                        .short('n')
                        .value_parser(value_parser!(String))
                        .default_value("cis")
                        .help("normalization method: cis, cis_unique, none")
                )
                .arg(
                    Arg::new("FIRST_CLUSTER")
                        .long("first-cluster")
                        .short('f')
                        .help("first cluster from hyperpartition")
                        .value_parser(value_parser!(String))
                        .default_value("none")
                        )
                .arg(
                    Arg::new("WHITELIST")
                        .long("whitelist")
                        .short('w')
                        .help("whitelist file, only keep the contigs in whitelist")
                        .value_parser(value_parser!(String))
                        .default_value("none")
                        )
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("4"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("prune")
                .about("Identity the allelic and cross-allelic contig pairs by raw allele table")
                .arg(arg!(<ALLELETABLE> "raw allele table"))
                .arg(arg!(<ALLELESTRANDTABLE> "allele table"))
                .arg(arg!(<CONTACTS> "contacts"))
                .arg(arg!(<PRUNETABLE> "output path of prune table"))
                .arg(
                    Arg::new("COUNTRE")
                        .long("count-re")
                        .short('c')
                        .value_parser(value_parser!(String))
                        .default_value("none")
                        .help("restriction enzyme count file")
                )
                .arg(
                    Arg::new("METHOD")
                        .long("method")
                        .short('m')
                        .value_parser(value_parser!(String))
                        .default_value("fast")
                        .help("method of prune: [fast, precise, greedy]")
                        )
                .arg(
                    Arg::new("NORMALIZATION_METHOD")
                        .long("normalization-method")
                        .short('n')
                        .value_parser(value_parser!(String))
                        .default_value("cis")
                        .help("normalization method, cis, cis_unique, none")
                ).arg(
                    Arg::new("FIRST_CLUSTER")
                        .long("first-cluster")
                        .short('f')
                        .help("first cluster from hyperpartition")
                        .value_parser(value_parser!(String))
                        .default_value("none")
                        )
                .arg(
                    Arg::new("WHITELIST")
                        .long("whitelist")
                        .short('w')
                        .help("whitelist file, only keep the contigs in whitelist")
                        .value_parser(value_parser!(String))
                        .default_value("none")
                        )
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("4"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("splitbam")
                .about("split bam by record number")
                .alias("split-bam")
                .arg(arg!(<BAM> "align bam from `dorado`"))
                .arg(
                    Arg::new("RECORD_NUM")
                        .long("record-num")
                        .short('n')
                        .value_parser(value_parser!(usize))
                        .default_value("1000000"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("output.split"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("mergeclm")
                .alias("clm-merge")
                .alias("merge-clm")
                .about("merge clm files")
                .arg(arg!(<CLM_DIR> "the dir contains clm files"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout")
                )

        )
        .subcommand(
            Command::new("splitclm")
                .alias("split-clm")
                .alias("clm-split")
                .about("Split clm by the cluster file.")
                .arg(arg!(<CLM> "clm"))
                .arg(arg!(<CLUSTER> "cluster"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .help("output dir, default splitclm")
                        .value_parser(value_parser!(String))
                        .default_value("./"))
        )
        .subcommand(
            Command::new("splitfastq")
                .about("split fastq by record number")
                .alias("splitfq")
                .arg(arg!(<FASTQ> "fastq"))
                .arg(
                    Arg::new("RECORD_NUM")
                        .long("record-num")
                        .short('n')
                        .value_parser(value_parser!(usize))
                        .default_value("1000000"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("output.split"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("extract-fasta")
                .about("extract fasta by a cluster file")
                .alias("split-fasta-by-cluster")
                .alias("split-fasta-by-clusters")
                .arg(arg!(<FASTA> "fasta"))
                .arg(arg!(<CLUSTERS> "clusters file"))
                .arg(
                    Arg::new("TRIM_LENGTH")
                        .long("trim-length")
                        .short('l')
                        .value_parser(value_parser!(usize))
                        .default_value("25000"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("slidefastq")
                .about("slide fastq")
                .alias("slidefq")
                .arg(arg!(<FASTQ> "fastq"))
                .arg(
                    Arg::new("WINDOW")
                        .long("window")
                        .short('w')
                        .value_parser(value_parser!(u64))
                        .default_value("5000"))
                .arg(
                    Arg::new("STEP")
                        .long("step")
                        .short('s')
                        .value_parser(value_parser!(u64))
                        .default_value("0"))
                .arg(
                    Arg::new("MIN_LENGTH")
                        .long("min-lenth")
                        .short('l')
                        .value_parser(value_parser!(u64))
                        .default_value("0")
                )
                .arg(
                    Arg::new("FILETYPE")
                        .long("filetype")
                        .short('f')
                        .value_parser(value_parser!(String))
                        .default_value("auto")
                        .help("filtype of sequences, auto dont support for stream input")
                )
                .arg(
                    Arg::new("COORDINATE")
                        .long("coordinate")
                        .short('c')
                        .action(ArgAction::SetTrue)
                        .default_value("false")
                        .help("add coordinate suffix of record id")
                )
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("slidefasta")
                .about("slide fasta")
                .alias("slidefa")
                .arg(arg!(<FASTA> "fasta"))
                .arg(
                    Arg::new("WINDOW")
                        .long("window")
                        .short('w')
                        .value_parser(value_parser!(u64))
                        .default_value("10000"))
                .arg(
                    Arg::new("STEP")
                        .long("step")
                        .short('s')
                        .value_parser(value_parser!(u64))
                        .default_value("0"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("slide2raw")
                .about("Convert slided read id to raw in bam file")
                .arg(arg!(<BAM> "slided read mapping bam"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("4"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("simulator")
                .about("simulating test data")
                .arg_required_else_help(true)
                .allow_external_subcommands(true)
                .subcommand(
                    Command::new("split-ont")
                        .about("simulate short from long read")
                        .arg(arg!(<BAM> "raw bam with MM/ML tags"))
                        .arg(
                            Arg::new("MIN_QUALITY")
                                .long("min-quality")
                                .short('q')
                                .value_parser(value_parser!(u8))
                                .default_value("40"))
                        .arg(
                            Arg::new("OUTPUT")
                                .long("output")
                                .short('o')
                                .value_parser(value_parser!(String))
                                .default_value("-")
                        .help("output file, default is stdout"))
                        .arg_required_else_help(true),
                ).subcommand(
                    Command::new("porec")
                        .about("simulate pore-c reads")
                        .arg(arg!(<FASTA> "fasta"))
                        .arg(arg!(<VCF> "vcf"))
                        .arg(arg!(<BED> "bed"))
                        .arg(
                            Arg::new("OUTPUT")
                                .long("output")
                                .short('o')
                                .value_parser(value_parser!(String))
                                .default_value("-")
                        .help("output file, default is stdout"))
                        .arg_required_else_help(true),
                        )   
                    .subcommand(
                        Command::new("hic")
                            .about("simulate hic reads")
                            .arg(arg!(<FASTA> "fasta"))
                            .arg(arg!(<VCF> "vcf"))
                            .arg(arg!(<BAM> "bam"))
                            .arg(
                                Arg::new("MIN_MAPQ")
                                    .long("--min-mapq")
                                    .short('q')
                                    .value_parser(value_parser!(u8))
                                    .default_value("1")
                            )
                            .arg(
                                Arg::new("THREADS")
                                    .long("threads")
                                    .short('t')
                                    .value_parser(value_parser!(usize))
                                    .default_value("4")
                            )
                            .arg(
                                Arg::new("OUTPUT")
                                    .long("output")
                                    .short('o')
                                    .value_parser(value_parser!(String))
                                    .default_value("-")
                            .help("output file, default is stdout"))
                            .arg_required_else_help(true),
                            )
        )
        .subcommand(
            Command::new("kmer")
                .about("some kmer operations")
                .arg_required_else_help(true)
                .allow_external_subcommands(true)
                .subcommand(
                    Command::new("count")
                        .about("count kmer")
                        .arg(arg!(<FASTA> "fasta"))
                        .arg(
                            Arg::new("K")
                                .long("k")
                                .short('k')
                                .value_parser(value_parser!(usize))
                                .default_value("19"))
                        .arg(
                            Arg::new("OUTPUT")
                                .long("output")
                                .short('o')
                                .value_parser(value_parser!(String))
                                .help("output file, default is stdout")
                                .default_value("-")
                        ).arg_required_else_help(true),
                )
                .subcommand(                
                    Command::new("mask")
                        .about("mask high frequency kmer")
                        .arg(arg!(<FASTA> "fasta"))
                        .arg(
                            Arg::new("K")
                                .long("k")
                                .short('k')
                                .value_parser(value_parser!(usize))
                                .default_value("19"))
                        .arg(
                            Arg::new("PLOIDY")
                                .long("ploidy")
                                .short('p')
                                .value_parser(value_parser!(u64))
                                .default_value("12")
                        )
                        .arg(
                            Arg::new("OUTPUT")
                                .long("output")
                                .short('o')
                                .value_parser(value_parser!(String))
                                .help("output file, default is stdout")
                                .default_value("-")
                        )
                        
                        .arg_required_else_help(true),
                )
                .subcommand(
                Command::new("position")
                    .about("export kmer positions to bed")
                    .arg_required_else_help(true)
                    .arg(arg!(<FASTA> "fasta"))
                    .arg(arg!(<KMER_LIST> "kmer list"))
                    .arg(
                        Arg::new("K")
                            .long("k")
                            .short('k')
                            .value_parser(value_parser!(usize))
                            .default_value("19")
                    )
                    .arg(
                        Arg::new("OUTPUT")
                            .long("output")
                            .short('o')
                            .value_parser(value_parser!(String))
                            .help("output file, default is stdout")
                            .default_value("-")
                    ).arg_required_else_help(true),

                    )
        )
        .subcommand(
            Command::new("digest")
                .about("digest genome by restriction enzyme, output restriction sites")
                .arg(arg!(<FASTA> "fasta"))
                .arg(
                    Arg::new("PATTERN")
                        .long("pattern")
                        .short('p')
                        .value_parser(value_parser!(String))
                        .default_value("GATC")
                        .help("restriction enzyme pattern, multiple pattern use comma to seperate"))
                .arg(
                        Arg::new("SLOPE")
                            .long("slope")
                            .short('s')
                            .value_parser(value_parser!(i64))
                            .default_value("30"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("count_re")
                .alias("countre")
                .about("count restriction enzyme sites, only support single enzyme")
                .arg(arg!(<FASTA> "fasta"))
                .arg(
                    Arg::new("PATTERN")
                        .long("pattern")
                        .short('p')
                        .value_parser(value_parser!(String))
                        .default_value("AAGCTT")
                        .help("restriction enzyme pattern, multiple pattern use comma to seperate"))
                .arg(
                    Arg::new("MIN_RE")
                        .long("min-re")
                        .short('r')
                        .value_parser(value_parser!(u64))
                        .default_value("1"))
                    
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("cutsite")
                .about("cut restriction site on pore-c reads")
                .arg(arg!(<FASTQ> "pore-c reads"))
                .arg(
                    Arg::new("PATTERN")
                        .long("pattern")
                        .short('p')
                        .value_parser(value_parser!(String))
                        .default_value("GATC"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("paf2depth")
                .about("Calculate depth from paf file")
                .arg(arg!(<PAF> "paf"))
                .arg(arg!(<CHROMSIZES> "chromsizes"))
                .arg(
                    Arg::new("WINSIZE")
                        .long("winsize")
                        .short('w')
                        .value_parser(value_parser!(usize))
                        .default_value("10000")
                )
                .arg(
                    Arg::new("STEPSIZE")
                        .long("stepsize")
                        .short('s')
                        .value_parser(value_parser!(usize))
                        .default_value("0")
                )
                .arg(
                    Arg::new("MIN_MAPQ")
                        .long("min-mapq")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("0")
                )
                .arg(
                    Arg::new("SECONDARY")
                        .long("secondary")
                        .action(ArgAction::SetTrue)
                        .help("include secondary alignments")
                        .value_parser(value_parser!(bool))
                        .default_value("false")
                )
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),

        )
        .subcommand(
            Command::new("paf2porec")
                .about("convert paf to concatemer (con) table")
                .alias("paf2concatemer")
                .alias("paf2concat")
                .alias("paf2pcon")
                .alias("paf2table")
                .arg(arg!(<PAF> "paf"))
                .arg(
                    Arg::new("BED")
                        .long("bed")
                        .short('b')
                        .value_parser(value_parser!(String))
                        .default_value(""))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg(
                    Arg::new("MIN_MAPQ")
                        .long("min-mapq")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("1"))
                .arg(
                    Arg::new("MIN_IDENTITY")
                        .long("min-identity")
                        .short('p')
                        .value_parser(value_parser!(f32))
                        .default_value("0.8"))
                .arg(
                    Arg::new("MIN_LENGTH")
                        .long("min-length")
                        .short('l')
                        .value_parser(value_parser!(u32))
                        .default_value("150"))
                .arg(
                    Arg::new("MAX_EDGE")
                        .long("min-edge")
                        .short('e')
                        .value_parser(value_parser!(u64))
                        .default_value("0")
                        .help("remove the alignments located in the edge of contigs")
                        
                )
                // .arg(
                //     Arg::new("MIN_ORDER")
                //         .long("min-order")
                //         .short('m')
                //         .value_parser(value_parser!(usize))
                //         .default_value("2")
                // )
                .arg(
                    Arg::new("MAX_ORDER")
                        .long("max-order")
                        .short('M')
                        .value_parser(value_parser!(u32))
                        .default_value("50")
                )
                .arg(
                    Arg::new("SECONDARY")
                        .long("secondary")
                        .action(ArgAction::SetTrue)
                        .help("include secondary alignments")
                        .value_parser(value_parser!(bool))
                        .default_value("false")
                )
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("porec2pairs")
                .about("convert concatemers (con) table to pairs")
                .alias("concatemer2pairs")
                .alias("con2pairs")
                .alias("pore2pairs")
                .alias("porec2pair")
                .arg(arg!(<TABLE> "pore-c table"))
                .arg(arg!(<CHROMSIZES> "chromsizes"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg(
                    Arg::new("MIN_MAPQ")
                        .long("min-mapq")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("1")
                        .help("minimum mapping quality of the alignment")
                    )
                .arg(
                    Arg::new("MIN_ORDER")
                        .long("min-order")
                        .value_parser(value_parser!(usize))
                        .default_value("2")
                        .help("min order of the concatemers")
                )
                .arg(
                    Arg::new("MAX_ORDER")
                        .long("max-order")
                        .value_parser(value_parser!(usize))
                        .default_value("50")
                        .help("max order of the concatemers")
                )
                .arg(
                    Arg::new("CHUNKSIZE")
                        .long("chunksize")
                        .short('c')
                        .value_parser(value_parser!(usize))
                        .default_value("1000000")
                        .help("chunksize of the pqs output, unused for pairs or pairs.gz output")
                )
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("porec-break")
                .about("Break contigs at break points.")
                .alias("concatemer-break")
                .alias("con-break")
                .arg(arg!(<TABLE> "pore-c table"))
                .arg(arg!(<BREAK_BED> "break points in bed format"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),

        )
        .subcommand(
            Command::new("porec-dup")
                .about("Break contigs at break points.")
                .alias("concatemer-dup")
                .alias("con-dup")
                .alias("porec-dup")
                .arg(arg!(<TABLE> "pore-c table"))
                .arg(arg!(<COLLAPSED> "collapsed contigs list, two columns with raw contigs and dup contigs."))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),

        )
        .subcommand(
            Command::new("porec-merge")
                .about("Merge multiple pore-c table file into single file")
                .alias("concatemer-merge")
                .alias("con-merge")
                .arg(
                    Arg::new("TABLES")
                        .action(ArgAction::Set)
                        .num_args(0..)
                )
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout")
                )
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("porec-intersect")
                .about("According a bed file to intersection a concatemer (con) table.")
                .alias("concatemer-intersect")
                .alias("con-intersect")
                .arg(arg!(<TABLE> "pore-c table"))
                .arg(arg!(<BED> "3-columns bed file"))
                .arg(
                    Arg::new("INVERT")
                        .long("invert")
                        .short('v')
                        .action(ArgAction::SetTrue)
                        .default_value("false")
                        .help("invert the selection")
                )
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout")
                    
                )
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("paf2pairs")
                .about("convert paf to pairs")
                .arg(arg!(<PAF> "paf"))
                .arg(arg!(<CHROMSIZES> "chromsizes"))
                .arg(
                    Arg::new("BED")
                        .long("bed")
                        .short('b')
                        .value_parser(value_parser!(String))
                        .default_value(""))
                .arg(
                    Arg::new("MIN_MAPQ")
                        .long("min-mapq")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("1")
                        .help("minimum mapping quality of the alignment")
                    )
                .arg(
                    Arg::new("MIN_IDENTITY")
                        .long("min-identity")
                        .short('p')
                        .value_parser(value_parser!(f32))
                        .default_value("0.8")
                        .help("minimum identity of the alignment")
                    )
                .arg(
                    Arg::new("MIN_LENGTH")
                        .long("min-length")
                        .short('l')
                        .value_parser(value_parser!(u32))
                        .default_value("150")
                        .help("minimum length of the alignment")
                    )
                .arg(
                    Arg::new("MAX_EDGE")
                        .long("min-edge")
                        .short('e')
                        .value_parser(value_parser!(u64))
                        .default_value("0")
                        .help("remove the alignments located in the edge of contigs")
                    )
                .arg(
                    Arg::new("MIN_ORDER")
                        .long("min-order")
                        .short('m')
                        .value_parser(value_parser!(usize))
                        .default_value("2")
                        .help("max order of the concatemers")
                    )
                .arg(
                    Arg::new("MAX_ORDER")
                        .long("max-order")
                        .short('M')
                        .value_parser(value_parser!(u32))
                        .default_value("50")
                        .help("max order of the concatemers")
                    )
                .arg(
                    Arg::new("SECONDARY")
                        .long("secondary")
                        .action(ArgAction::SetTrue)
                        .help("include secondary alignments")
                        .value_parser(value_parser!(bool))
                        .default_value("false")
                )
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout")
                )
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs-downsample")
                .alias("down-pairs")
                .alias("downsample-pairs")
                .alias("downpairs")
                .about("downsample pairs")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(
                    Arg::new("NUMBER")
                        .long("number")
                        .short('n')
                        .value_parser(value_parser!(usize))
                        .default_value("1000000"))
            
                .arg(
                    Arg::new("PERCENT")
                        .long("percent")
                        .short('p')
                        .value_parser(value_parser!(f64))
                        .default_value("0.0"))
                .arg(
                    Arg::new("SEED")
                        .long("seed")
                        .short('s')
                        .value_parser(value_parser!(usize))
                        .default_value("42"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs-merge")
                .alias("pairsmerge")
                .alias("merge-pairs")
                .about("merge multiple pairs to one")
                .arg(
                    Arg::new("FILES")
                        .action(ArgAction::Set)
                        .num_args(0..)
                )
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout")
                )
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs-filter")
                .alias("filterpairs")
                .alias("filter-pairs")
                .about("filter pairs by mapq")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(
                    Arg::new("MIN_QUALITY")
                        .long("min-quality")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("1"))
                .arg(
                    Arg::new("WHITELIST")
                        .long("whitelist")
                        .short('w')
                        .help("whitelist file, only keep the contigs in whitelist")
                        .value_parser(value_parser!(String))
                        .default_value("none")
                        )
                .arg(Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs-break")
                .about("Break contigs at chimeric points follwed a bed")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(arg!(<BREAK_BED> "break contigs with a bed format"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs-dup")
                .about("dup collapsed contigs by collapsed rescue")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(arg!(<COLLAPSED> "collapsed contigs with raw contig and duplicated contigs"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs-split")
                .about("split pairs by chunksize")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(
                    Arg::new("CHUNKSIZE")
                        .long("chunksize")
                        .short('c')
                        .value_parser(value_parser!(usize))
                        .default_value("10000000"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("output.split"))
                .arg_required_else_help(true),

        )
        .subcommand(
            Command::new("pairs2contacts")
                .alias("pairs2contact")
                .about("calculate the contacts between contigs")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(Arg::new("MIN_CONTACTS")
                        .long("min-contacts")
                        .short('c')
                        .value_parser(value_parser!(u32))
                        .default_value("1"))
                .arg(
                    Arg::new("MIN_QUALITY")
                        .long("min-quality")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("1"))
                .arg(
                    Arg::new("SPLIT_NUM")
                        .long("split-num")
                        .short('n')
                        .value_parser(value_parser!(u32))
                        .default_value("1"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs2clm")
                .about("convert pairs to clm file, which is used for `allhic optimize`")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(Arg::new("MIN_CONTACTS")
                        .long("min-contacts")
                        .short('c')
                        .value_parser(value_parser!(u32))
                        .default_value("1"))
                .arg(
                    Arg::new("MIN_QUALITY")
                        .long("min-quality")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("0"))
                .arg(
                    Arg::new("NO_OUTPUT_SPLIT_CONTACTS")
                        .long("no-output-split")
                        .action(ArgAction::SetTrue)
                        .default_value("false")
                        .help("Dont output split contacts."))
                .arg(
                    Arg::new("OUTPUT_DEPTH")
                        .short('d')
                        .long("output-depth")
                        .action(ArgAction::SetTrue)
                        .default_value("false")
                        .help("The path of ooutput depth."))
                .arg(
                    Arg::new("BINSIZE")
                        .long("binsize")
                        .short('b')
                        .value_parser(value_parser!(u32))
                        .default_value("10000")
                )

                // .arg(
                //     Arg::new("LOW_MEMORY")
                //         .long("low-memory")
                //         .action(ArgAction::SetTrue)
                //         .default_value("false")
                //         .help("use low memory mode, which is slower but use less memory."))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("4"))
                .arg(Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs2depth")
                .about("convert pairs to depth file")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(
                    Arg::new("BINSIZE")
                        .long("binsize")
                        .short('b')
                        .value_parser(value_parser!(u32))
                        .default_value("10000")
                )
                .arg(
                    Arg::new("MIN_QUALITY")
                        .long("min-quality")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("0"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs2mnd")
                .about("convert pairs to mnd file")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(
                    Arg::new("MIN_QUALITY")
                        .long("min-quality")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("1"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        ).subcommand(
            Command::new("pairs2bam")
                .about("convert pairs to pseudo bam file")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(
                    Arg::new("MIN_QUALITY")
                        .long("min-quality")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("1"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("4"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs2pqs")
                .hide(true)
                .about("convert pairs to pairs.pqs file")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(
                    Arg::new("CHUNKSIZE")
                        .long("chunksize")
                        .short('c')
                        .value_parser(value_parser!(usize))
                        .default_value("1000000")
                )
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("output.pqs")
                        .help("output dir, default is output.pqs"))
                .arg_required_else_help(true),
                    
        )
        .subcommand(
            Command::new("bam2paf")
            .about("convert dorado align bam to paf")
            .arg(arg!(<BAM> "bam file should be sorted by read name, dont sort it by coordinate"))
            .arg(
                Arg::new("SECONDARY")
                    .long("secondary")
                    .short('s')
                    .value_parser(value_parser!(bool))
                    .action(ArgAction::SetTrue)
                    .default_value("false")
                    .help("Is output secondary, default is false")
            )
            .arg(
                Arg::new("THREADS")
                    .long("threads")
                    .short('t')
                    .value_parser(value_parser!(usize))
                    .default_value("8"))
            .arg(
                Arg::new("OUTPUT")
                    .long("output")
                    .short('o')
                    .value_parser(value_parser!(String))
                    .default_value("-")
                    .help("output file, default is stdout"))
            .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("bam2fastq")
                .about("convert bam to fastq file")
                .arg(arg!(<BAM> "bam"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )

        .subcommand(
            Command::new("bam2fasta")
                .about("convert bam to fasta file")
                .arg(arg!(<BAM> "bam"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )

        .subcommand(
            Command::new("bamstat")
                .about("stat the sequences in bam file")
                .arg(
                    Arg::new("BAM")
                        .action(ArgAction::Set)
                        .num_args(0..)
                )
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )

        .subcommand(
            Command::new("hicbamstat")
                .about("stat the hic bam")
                .hide(true)
                .arg(
                    Arg::new("BAM")
                        .action(ArgAction::Set)
                        .num_args(0..)
                )
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("porecbamstat")
                .about("stat the porec bam")
                .hide(true)
                .arg(
                    Arg::new("BAM")
                        .action(ArgAction::Set)
                        .num_args(0..)
                )
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("bam2pairs")
                .about("convert paired read align bam to pairs, only support for paired end reads")
                .arg(arg!(<BAM> "bam"))
                .arg(
                    Arg::new("MIN_QUALITY")
                        .long("min-quality")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("0"))
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("pairs-intersect")
                .about("According a bed file to intersection a pairs file.")
                .arg(arg!(<PAIRS> "pairs"))
                .arg(arg!(<BED> "3-columns bed file"))
                .arg(
                    Arg::new("INVERT")
                        .long("invert")
                        .short('v')
                        .action(ArgAction::SetTrue)
                        .default_value("false")
                        .help("invert the selection")
                )
                .arg(
                    Arg::new("MIN_QUALITY")
                        .long("min-quality")
                        .short('q')
                        .value_parser(value_parser!(u8))
                        .default_value("1"))
                .arg(
                    Arg::new("EDGE_LENGTH")
                        .long("edge-length")
                        .short('e')
                        .value_parser(value_parser!(u64))
                        .default_value("0")
                        .hide(true)
                        .help("remove the alignments located in the edge of contigs")
                )
                .arg(
                    Arg::new("THREADS")
                        .long("threads")
                        .short('t')
                        .value_parser(value_parser!(usize))
                        .default_value("8"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout")
                    
                )
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("chromsizes")
                .about("generate chromsizes file")
                .alias("contigsizes")
                .arg(arg!(<FASTA> "fasta"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),

        )
        .subcommand(
            Command::new("prunepairs")
                .about("prune pairs")
                .hide(true)
                .arg(arg!(<PAIRS> "pairs"))
                .arg(arg!(<PRUNE> "Prune contigs"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
                
        )
        .subcommand(
            Command::new("modbam2fq")
                .about("convert modified bam to fastq with modified base")
                .arg(arg!(<BAM> "modified bam"))
                .arg(
                    Arg::new("MIN_PROB")
                        .long("min-prob")
                        .short('p')
                        .value_parser(value_parser!(f32))
                        .default_value("0.75"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("modfa")
                .about("modify fasta by bedMethy file")
                .arg(arg!(<FASTA> "fasta"))
                .arg(arg!(<BED> "bed"))
                .arg(
                    Arg::new("MIN_FRAC")
                        .long("min-frac")
                        .short('f')
                        .value_parser(value_parser!(f64))
                        .default_value("0.5"))
                .arg(
                    Arg::new("OUTPUT")
                        .long("output")
                        .short('o')
                        .value_parser(value_parser!(String))
                        .default_value("-")
                        .help("output file, default is stdout"))
                .arg_required_else_help(true),
        )
        .subcommand(
            Command::new("optimize")
            .hide(true)
            .about("optimize contigs (developing)")
            .arg(arg!(<SCORE> "score"))
            .arg(
                Arg::new("OUTPUT")
                    .long("output")
                    .short('o')
                    .value_parser(value_parser!(String))
                    .default_value("-")
                        .help("output file, default is stdout"))
            .arg_required_else_help(true),
      )
        
}
